---
title: "analysis"
author: "Dan Birman"
date: "Thursday, February 19, 2015"
output: html_document
---

```{r}
library(jsonlite)
```

```{r}
## windows code
# data = fromJSON(txt="C:\\Users\\Dan\\proj\\repo254\\sandbox-results\\3M23Y66PO3JLAD1Z98J7EGJJDYHS6P.json")
data = fromJSON(txt="sandbox-results/34FNN24DCNLMNVDU3V1R4WTKYOA5Y8.json")
# pull out the 'answer' variable
ans = data$answer
# get the big picture data
fingerprint = ans$fingerprint
screenInfo = data.frame(width = id_info$screenWidth,height=id_info$screenHeight,colors=id_info$colorDepth,browser=id_info$browser)
# now get the trial data
training = ans$t_train
critical = ans$t_critical
backg = ans$t_backg
stream = ans$t_stream
trials = ans$trialInfo
```

Parse data to group performance
```{r}
if (trials$backgtask[6]==1) {
  backg_pos = c(6:10)
  notbackg = c(11:15)
} else {
  backg_pos = c(11:15)
  notbackg = c(6:10)
}
trials$correct[1:15] = 0
trials$correct[1:4] = training$regResp == trials$digits[1:4]
trials$correct[notbackg] = stream$regResp == trials$digits[notbackg]
trials$correct[5] = critical$catchImageResp == trials$catchImage[5]
trials$correct[backg_pos] = backg$catchImageResp == trials$catchImage[backg_pos]
```

```{r}
train_perf = mean(trials$correct[1:4])
crit_perf = trials$correct[5]
backg_perf = mean(trials$correct[backg_pos])
stream_perf = mean(trials$correct[notbackg])
```
